import { getToday, getTommorow } from "src/libs/dateFunc";
import type { ListTodo } from "src/types";

export const EXAMPLE_MY_TODO_LIST: ListTodo[] = [
  {
    id: "11",
    task: `Next.js, Tailwind CSS, Prettier, ESLint, React Query, Jest, Turborepo, Firebase Authentication, PlanetScale, Vercelを使いこなして、ポートフォリオ用のWebサービスを作る。バックエンドには、typescript、Node.js、Express,Prisma、Docker、Cloud Runを使って開発する。`,
    userId: "",
    sortKey: 3,
    dueDate: null,
    completeDate: null,
    isDone: false,
    createAt: getToday(),
    updateAt: getToday(),
  },
  {
    id: "10",
    task: `機械学習の情報収集をする`,
    userId: "",
    sortKey: 2,
    dueDate: null,
    completeDate: null,
    isDone: false,
    createAt: getToday(),
    updateAt: getToday(),
  },
  {
    id: "9",
    task: `QinTodoの開発状況を報告する`,
    userId: "",
    sortKey: 2,
    dueDate: getTommorow(),
    completeDate: null,
    isDone: false,
    createAt: getToday(),
    updateAt: getToday(),
  },
  {
    id: "8",
    task: `QinTodoの開発をする`,
    userId: "",
    sortKey: 6,
    dueDate: getToday(),
    completeDate: null,
    isDone: false,
    createAt: getToday(),
    updateAt: getToday(),
  },
  {
    id: "7",
    task: `AWSの資格試験を受験する`,
    userId: "",
    sortKey: 5,
    dueDate: getToday(),
    completeDate: null,
    isDone: false,
    createAt: getToday(),
    updateAt: getToday(),
  },
  {
    id: "6",
    task: `QinのReact講座で勉強する`,
    userId: "",
    sortKey: 4,
    dueDate: getToday(),
    completeDate: null,
    isDone: false,
    createAt: getToday(),
    updateAt: getToday(),
  },
  {
    id: "5",
    task: `書籍を使って学ぶのは本当に必要なのか考察する。`,
    userId: "",
    sortKey: 3,
    dueDate: getToday(),
    completeDate: null,
    isDone: false,
    createAt: getToday(),
    updateAt: getToday(),
  },
  {
    id: "4",
    task: `HTML・CSS・JavaScriptの実践。`,
    userId: "",
    sortKey: 2,
    dueDate: getToday(),
    completeDate: getToday(),
    isDone: true,
    createAt: getToday(),
    updateAt: getToday(),
  },
  {
    id: "3",
    task: `3年後にどうなっていたいかを考える。`,
    userId: "",
    sortKey: 1,
    dueDate: getTommorow(),
    completeDate: null,
    isDone: false,
    createAt: getToday(),
    updateAt: getToday(),
  },
  {
    id: "2",
    task: `TypeScriptが何か調べてる。`,
    userId: "",
    sortKey: 1,
    dueDate: null,
    completeDate: null,
    isDone: false,
    createAt: getToday(),
    updateAt: getToday(),
  },
  {
    id: "1",
    task: `Reactのチュートリアルを学んでみた感想まとめる。`,
    userId: "",
    sortKey: 1,
    dueDate: getToday(),
    completeDate: getTommorow(),
    isDone: true,
    createAt: getToday(),
    updateAt: getTommorow(),
  },
];
